// Mocks generated by Mockito 5.4.6 from annotations
// in book_log/test/feature/book/domain/usecase/add_book_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:book_log/feature/book/domain/entity/book.dart' as _i5;
import 'package:book_log/feature/book/domain/entity/book_search_result.dart'
    as _i4;
import 'package:book_log/feature/book/domain/repository/book_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i2.BookRepository {
  MockBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BookSearchResult>> searchBooks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchBooks, [query]),
            returnValue: _i3.Future<List<_i4.BookSearchResult>>.value(
              <_i4.BookSearchResult>[],
            ),
          )
          as _i3.Future<List<_i4.BookSearchResult>>);

  @override
  _i3.Future<List<_i4.BookSearchResult>> getBestsellers() =>
      (super.noSuchMethod(
            Invocation.method(#getBestsellers, []),
            returnValue: _i3.Future<List<_i4.BookSearchResult>>.value(
              <_i4.BookSearchResult>[],
            ),
          )
          as _i3.Future<List<_i4.BookSearchResult>>);

  @override
  _i3.Future<void> addBook(_i5.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#addBook, [book]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Book>> getBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getBooks, []),
            returnValue: _i3.Future<List<_i5.Book>>.value(<_i5.Book>[]),
          )
          as _i3.Future<List<_i5.Book>>);

  @override
  _i3.Future<void> updateStatus(String? bookId, _i5.ReadingStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [bookId, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
