// Mocks generated by Mockito 5.4.6 from annotations
// in book_log/test/feature/book/domain/usecase/get_sentences_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:book_log/feature/book/domain/entity/sentence.dart' as _i4;
import 'package:book_log/feature/book/domain/repository/sentence_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SentenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSentenceRepository extends _i1.Mock
    implements _i2.SentenceRepository {
  MockSentenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addSentence(
    String? bookId,
    String? content, {
    int? pageNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addSentence,
              [bookId, content],
              {#pageNumber: pageNumber},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Sentence>> getSentences(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getSentences, [bookId]),
            returnValue: _i3.Future<List<_i4.Sentence>>.value(<_i4.Sentence>[]),
          )
          as _i3.Future<List<_i4.Sentence>>);

  @override
  _i3.Future<void> setRepresentative(String? bookId, String? sentenceId) =>
      (super.noSuchMethod(
            Invocation.method(#setRepresentative, [bookId, sentenceId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
